language: node_js
node_js:
  - "12"
  - "10"
  - "8"

before_install:
  # Install latest npm to avoid semver issues
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

  # Upgrade Ruby
  - rvm install 2.1.1
  - rvm --default use 2.1.1

install:
  # Install node modules
  - npm install

  # Install gem and sass
  - ruby --version
  - wget http://production.cf.rubygems.org/rubygems/rubygems-2.1.7.tgz
  - tar xvf rubygems-2.1.7.tgz
  - cd rubygems-2.1.7
  - sudo ruby setup.rb
  - cd ..
  - gem --version
  - gem install sass
  - sass --version

  # Install libsass/sassc
  - git clone https://github.com/hcatlin/libsass.git libsass
  - cd libsass
  - git checkout 3.0.2
  - cd -
  - export SASS_LIBSASS_PATH=$PWD/libsass
  - git clone https://github.com/hcatlin/sassc.git sassc
  - cd sassc
  - git checkout 3.0.2
  - make
  - sudo ln -s $PWD/bin/sassc /usr/local/bin/sassc
  - cd ..
  - sassc -h

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
